family = input("Enter a noun - plural and without a capital letter: ")
sisters = input("Enter a noun - plural and without a capital letter: ")
Get_up = input("Enter a verb - with a capital letter: ")
sing = input("Enter a different verb - without a capital letter: ")


print("We are " + family)
print("I got all my " + sisters + " with me")
print("We are " + family)
print(Get_up + ", everybody, and " + sing)
print("We are " + family)
print("I got all my " + sisters + " with me")
print("We are " + family)
print(Get_up + ", everybody, and " + sing)
print(" ")
print("Everyone can see we're together")
print("As we walk on by")
print("And we flock just like birds of a feather")
print("I won't tell no lie")
print("All of the people around us, they say")
print("Can they be that close?")
print("Just let me state for the record")
print("We're giving love in a family dose")